### ISSUE TITLE
Mouse control

### ISSUE THREAD

**Issue by abrindam** [abrindam/ArtemisEngineeringClient#5]
The client is meant to be heavily keyboard oriented but it wouldn't hurt to support the mouse as well.

**Comment by jacobmaxfrank** [comment]
Unless you want to allow dispatching damcom teams to damaged nodes of a specific system by clicking on that system's health bar, I don't see what other mouse control we'd want.

**Comment by jacobmaxfrank** [comment]
Actually, here's another idea: hovering over a system's health bar should highlight nodes belonging to that system.  That way it's easy to get a sense of which nodes are where and particularly which nodes you need to send DAMCON teams to in order to effect targeted repairs.  Transparency (less for that system's nodes or just way more for other nodes) and/or blink are good options.
